#!/usr/bin/env python3

import os
import sys

from dailyfx_agent import main


if __name__ == "__main__":
    exit_code = main()
    if exit_code == 0 and any(arg in {"--daemon", "-d"} for arg in sys.argv[1:]):
        sys.stdout.flush()
        sys.stderr.flush()
        os._exit(0)
    raise SystemExit(exit_code)
