"""initial_baseline

Revision ID: 0001_initial_baseline
Revises:
Create Date: 2026-10-04 10:22:37.020074
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_initial_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_effects",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_group", sa.String(length=255), nullable=True),
        sa.Column("positive_prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("custom_prompt_placeholder", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("builtin_hash", sa.String(length=128), nullable=True),
        sa.Column("latest_builtin_hash", sa.String(length=128), nullable=True),
        sa.Column("user_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_usage_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usage_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_usage_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_usage_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_usage_events_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_usage_events_usage_type"), ["usage_type"], unique=False)

    op.create_table(
        "ai_usage_locks",
        sa.Column("usage_type", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("usage_type"),
    )
    op.bulk_insert(
        sa.table("ai_usage_locks", sa.column("usage_type", sa.String)),
        [{"usage_type": "vision"}, {"usage_type": "image"}],
    )
    op.create_table(
        "asset_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("generation_type", sa.String(length=50), nullable=False),
        sa.Column("usage_source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "asset_id", name="uq_asset_usage_task_asset"),
    )
    with op.batch_alter_table("asset_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_usage_accepted_at"), ["accepted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_schedule_id"), ["schedule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_task_id"), ["task_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("source_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("changes_json", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_event_id"), ["event_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_outcome"), ["outcome"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_schedule_id"), ["schedule_id"], unique=False)
        batch_op.create_index("ix_audit_events_target", ["target_type", "target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_task_id"), ["task_id"], unique=False)

    op.create_table(
        "effect_presets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("groups_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "effect_statistics_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("effect_id", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("liked", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("effect_statistics_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_effect_statistics_log_effect_id"),
            ["effect_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_effect_statistics_log_task_id"), ["task_id"], unique=True)

    op.create_table(
        "file_deletion_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file_deletion_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_deletion_jobs_next_attempt_at"),
            ["next_attempt_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_file_deletion_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_deletion_jobs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "generation_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("generation_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_asset_ids", sa.Text(), nullable=False),
        sa.Column("output_path", sa.Text(), nullable=True),
        sa.Column("local_file_status", sa.String(length=30), nullable=False),
        sa.Column("local_file_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_file_delete_reason", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("total_token_count", sa.Integer(), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("tags_json", sa.Text(), nullable=True),
        sa.Column("task_step", sa.String(length=255), nullable=True),
        sa.Column("output_format", sa.String(length=10), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_asset_id", sa.String(length=64), nullable=True),
        sa.Column("upload_status", sa.String(length=50), nullable=True),
        sa.Column("album_id", sa.String(length=64), nullable=True),
        sa.Column("album_name", sa.String(length=255), nullable=True),
        sa.Column("album_created", sa.Boolean(), nullable=False),
        sa.Column("album_updated", sa.Boolean(), nullable=False),
        sa.Column("accept_notes", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_generation_history_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_generation_history_schedule_id"),
            ["schedule_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_generation_history_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_history_task_id"), ["task_id"], unique=True)
        batch_op.create_index(
            "ix_generation_history_type_created_at",
            ["generation_type", "created_at"],
            unique=False,
        )

    op.create_table(
        "generation_stream_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_stream_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generation_stream_events_event_type"),
            ["event_type"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_generation_stream_events_task_id"), ["task_id"], unique=False)

    op.create_table(
        "generation_tasks",
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("step", sa.String(length=64), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("parent_task_id", sa.String(length=64), nullable=True),
        sa.Column("root_task_id", sa.String(length=64), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=64), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    with op.batch_alter_table("generation_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_generation_tasks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_generation_tasks_heartbeat_at"),
            ["heartbeat_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_generation_tasks_priority"), ["priority"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_generation_tasks_root_task_id"),
            ["root_task_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_generation_tasks_schedule_id"), ["schedule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_status"), ["status"], unique=False)

    op.create_table(
        "notification_presets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("encrypted_token", sa.Text(), nullable=True),
        sa.Column("webhook_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "people_presets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("album_ids_json", sa.Text(), nullable=True),
        sa.Column("person_filters_json", sa.Text(), nullable=True),
        sa.Column("start_date", sa.String(length=20), nullable=True),
        sa.Column("end_date", sa.String(length=20), nullable=True),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.String(length=512), nullable=False),
        sa.Column("auth", sa.String(length=256), nullable=False),
        sa.Column("device_label", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("immich_url", sa.String(length=2048), nullable=True),
        sa.Column("encrypted_immich_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_openai_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_gemini_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_openrouter_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_byteplus_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_xiaomi_api_key", sa.String(), nullable=True),
        sa.Column("encrypted_local_ai_api_key", sa.String(), nullable=True),
        sa.Column("local_ai_base_url", sa.String(length=2048), nullable=True),
        sa.Column("ai_vision_hourly_limit", sa.Integer(), nullable=False),
        sa.Column("ai_image_hourly_limit", sa.Integer(), nullable=False),
        sa.Column("debug_mode", sa.Boolean(), nullable=False),
        sa.Column("favorite_albums_json", sa.Text(), nullable=True),
        sa.Column("ai_custom_prompt", sa.Text(), nullable=True),
        sa.Column("retention_enabled", sa.Boolean(), nullable=False),
        sa.Column("retention_rejected_files_days", sa.Integer(), nullable=True),
        sa.Column("retention_rejected_metadata_days", sa.Integer(), nullable=True),
        sa.Column("retention_failed_files_days", sa.Integer(), nullable=True),
        sa.Column("retention_failed_metadata_days", sa.Integer(), nullable=True),
        sa.Column("retention_uploaded_files_days", sa.Integer(), nullable=True),
        sa.Column("retention_uploaded_metadata_days", sa.Integer(), nullable=True),
        sa.Column("retention_task_days", sa.Integer(), nullable=True),
        sa.Column("retention_audit_days", sa.Integer(), nullable=True),
        sa.Column("retention_backup_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vapid_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preset_push_subscriptions",
        sa.Column("notification_preset_id", sa.Integer(), nullable=False),
        sa.Column("push_subscription_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notification_preset_id"], ["notification_presets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["push_subscription_id"], ["push_subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_preset_id", "push_subscription_id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("schedule_expr", sa.String(length=100), nullable=False),
        sa.Column("people_preset_id", sa.Integer(), nullable=False),
        sa.Column("effect_preset_id", sa.Integer(), nullable=False),
        sa.Column("album_name", sa.String(length=255), nullable=False),
        sa.Column("ai_vision_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_vision_model", sa.String(length=100), nullable=False),
        sa.Column("ai_image_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_image_model", sa.String(length=100), nullable=False),
        sa.Column("ai_prompt_enrichment", sa.Boolean(), nullable=False),
        sa.Column("ai_photo_selection_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_tick_status", sa.String(length=50), nullable=True),
        sa.Column("last_tick_reason", sa.Text(), nullable=True),
        sa.Column("last_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["effect_preset_id"],
            ["effect_presets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["people_preset_id"],
            ["people_presets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedules_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_schedules_is_deleted"), ["is_deleted"], unique=False)

    op.create_table(
        "schedule_notification_presets",
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("notification_preset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notification_preset_id"], ["notification_presets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("schedule_id", "notification_preset_id"),
    )

    # Widen alembic_version.version_num to VARCHAR(255) for future long revision IDs
    with op.batch_alter_table("alembic_version", schema=None) as batch_op:
        batch_op.alter_column(
            "version_num",
            type_=sa.String(255),
            existing_type=sa.String(32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_notification_presets")
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_schedules_enabled"))

    op.drop_table("schedules")
    op.drop_table("preset_push_subscriptions")
    op.drop_table("vapid_keys")
    op.drop_table("settings")
    op.drop_table("push_subscriptions")
    op.drop_table("people_presets")
    op.drop_table("notification_presets")
    with op.batch_alter_table("generation_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_source"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_root_task_id"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_priority"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_heartbeat_at"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_created_at"))

    op.drop_table("generation_tasks")
    with op.batch_alter_table("generation_stream_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_stream_events_task_id"))
        batch_op.drop_index(batch_op.f("ix_generation_stream_events_event_type"))

    op.drop_table("generation_stream_events")
    with op.batch_alter_table("generation_history", schema=None) as batch_op:
        batch_op.drop_index("ix_generation_history_type_created_at")
        batch_op.drop_index(batch_op.f("ix_generation_history_task_id"))
        batch_op.drop_index(batch_op.f("ix_generation_history_status"))
        batch_op.drop_index(batch_op.f("ix_generation_history_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_generation_history_created_at"))

    op.drop_table("generation_history")
    with op.batch_alter_table("file_deletion_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_deletion_jobs_task_id"))
        batch_op.drop_index(batch_op.f("ix_file_deletion_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_file_deletion_jobs_next_attempt_at"))

    op.drop_table("file_deletion_jobs")
    with op.batch_alter_table("effect_statistics_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_effect_statistics_log_task_id"))
        batch_op.drop_index(batch_op.f("ix_effect_statistics_log_effect_id"))

    op.drop_table("effect_statistics_log")
    op.drop_table("effect_presets")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_task_id"))
        batch_op.drop_index("ix_audit_events_target")
        batch_op.drop_index(batch_op.f("ix_audit_events_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_outcome"))
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_category"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    with op.batch_alter_table("asset_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_usage_task_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_status"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_asset_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_accepted_at"))

    op.drop_table("asset_usage")
    op.drop_table("ai_usage_locks")
    with op.batch_alter_table("ai_usage_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_usage_type"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_task_id"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_events_created_at"))

    op.drop_table("ai_usage_events")
    op.drop_table("ai_effects")

    # Widen alembic_version.version_num to VARCHAR(255) for future long revision IDs
    with op.batch_alter_table("alembic_version", schema=None) as batch_op:
        batch_op.alter_column(
            "version_num",
            type_=sa.String(255),
            existing_type=sa.String(32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
