"""expand_generation_tasks_table

Revision ID: 2b9a7c90cff1
Revises: 9ad868058887
Create Date: 2026-07-11 21:14:15.396304
"""

import sqlalchemy as sa
from alembic import op

import app.database

revision = "2b9a7c90cff1"
down_revision = "9ad868058887"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_effects", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("generation_tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source", sa.String(length=20), server_default="run_now", nullable=False))
        batch_op.add_column(sa.Column("schedule_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("priority", sa.String(length=10), server_default="normal", nullable=False))
        batch_op.add_column(sa.Column("attempt", sa.Integer(), server_default="1", nullable=False))
        batch_op.add_column(sa.Column("parent_task_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("root_task_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("max_attempts", sa.Integer(), server_default="1", nullable=False))
        batch_op.add_column(
            sa.Column(
                "queued_at",
                app.database.UTCDateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("started_at", app.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("finished_at", app.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("cancel_requested_at", app.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("cancelled_at", app.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("worker_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("heartbeat_at", app.database.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("error_code", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("error_retryable", sa.Boolean(), server_default=sa.text("0"), nullable=False))
        batch_op.create_index(batch_op.f("ix_generation_tasks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_heartbeat_at"), ["heartbeat_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_root_task_id"), ["root_task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_schedule_id"), ["schedule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_generation_tasks_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generation_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_tasks_source"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_root_task_id"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_priority"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_heartbeat_at"))
        batch_op.drop_index(batch_op.f("ix_generation_tasks_created_at"))
        batch_op.drop_column("error_retryable")
        batch_op.drop_column("error_code")
        batch_op.drop_column("heartbeat_at")
        batch_op.drop_column("worker_id")
        batch_op.drop_column("cancelled_at")
        batch_op.drop_column("cancel_requested_at")
        batch_op.drop_column("finished_at")
        batch_op.drop_column("started_at")
        batch_op.drop_column("queued_at")
        batch_op.drop_column("max_attempts")
        batch_op.drop_column("root_task_id")
        batch_op.drop_column("parent_task_id")
        batch_op.drop_column("attempt")
        batch_op.drop_column("priority")
        batch_op.drop_column("schedule_id")
        batch_op.drop_column("source")

    with op.batch_alter_table("ai_effects", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    # ### end Alembic commands ###
