"""add_byteplus_api_key

Revision ID: 2f3fe6dbc8ae
Revises: 008cc3fba906
Create Date: 2026-05-27 09:46:09.983564
"""
from alembic import op
import sqlalchemy as sa


revision = '2f3fe6dbc8ae'
down_revision = '008cc3fba906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_byteplus_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('encrypted_byteplus_api_key')

    # ### end Alembic commands ###

