"""create_asset_usage_table

Revision ID: 87a2437392f5
Revises: 0036
Create Date: 2026-07-11 11:38:00.137441
"""

import sqlalchemy as sa
from alembic import op

import app.database

revision = "87a2437392f5"
down_revision = "0036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("generation_type", sa.String(length=50), nullable=False),
        sa.Column("usage_source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("selected_at", app.database.UTCDateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", app.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("released_at", app.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            app.database.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.database.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "asset_id", name="uq_asset_usage_task_asset"),
    )
    with op.batch_alter_table("asset_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_usage_accepted_at"), ["accepted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_schedule_id"), ["schedule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_usage_task_id"), ["task_id"], unique=False)

    with op.batch_alter_table("collage_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collage_history_task_id"))

    op.drop_table("collage_history")
    with op.batch_alter_table("ai_effects", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("collage_output_size")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collage_output_size", sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table("ai_effects", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    op.create_table(
        "collage_history",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("task_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("summary", sa.TEXT(), nullable=False),
        sa.Column("layout", sa.VARCHAR(length=100), nullable=False),
        sa.Column("proposal_json", sa.TEXT(), nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), server_default=sa.text("'gemini'"), nullable=False),
        sa.Column("model", sa.VARCHAR(length=100), server_default=sa.text("'gemini-2.5-flash'"), nullable=False),
        sa.Column("asset_count", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("total_token_count", sa.INTEGER(), nullable=True),
        sa.Column("image_path", sa.TEXT(), nullable=True),
        sa.Column("image_url", sa.TEXT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), server_default=sa.text("'SUCCESS'"), nullable=False),
        sa.Column("uploaded_asset_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("upload_status", sa.VARCHAR(length=50), nullable=True),
        sa.Column("album_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("album_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("album_created", sa.BOOLEAN(), server_default=sa.text("0"), nullable=False),
        sa.Column("album_updated", sa.BOOLEAN(), server_default=sa.text("0"), nullable=False),
        sa.Column("accepted_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collage_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collage_history_task_id"), ["task_id"], unique=1)

    with op.batch_alter_table("asset_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_usage_task_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_status"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_asset_id"))
        batch_op.drop_index(batch_op.f("ix_asset_usage_accepted_at"))

    op.drop_table("asset_usage")
    # ### end Alembic commands ###
