"""Add GenerationHistoryModel and update SettingsModel

Revision ID: cf1791cf9d4b
Revises: 0008_add_collage_filter_style
Create Date: 2026-05-14 13:48:42.442475
"""
from alembic import op
import sqlalchemy as sa


revision = 'cf1791cf9d4b'
down_revision = '0008_add_collage_filter_style'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_asset_ids', sa.Text(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('total_token_count', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('uploaded_asset_id', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.String(length=50), nullable=True),
    sa.Column('album_id', sa.String(length=64), nullable=True),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('album_created', sa.Boolean(), nullable=False),
    sa.Column('album_updated', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_task_id'), 'generation_history', ['task_id'], unique=True)
    op.add_column('settings', sa.Column('automation_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('settings', sa.Column('automation_schedule', sa.String(length=50), server_default='weekly', nullable=False))
    op.add_column('settings', sa.Column('automation_filter_json', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('modification_groups_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'modification_groups_json')
    op.drop_column('settings', 'automation_filter_json')
    op.drop_column('settings', 'automation_schedule')
    op.drop_column('settings', 'automation_enabled')
    op.drop_index(op.f('ix_generation_history_task_id'), table_name='generation_history')
    op.drop_table('generation_history')
    # ### end Alembic commands ###

