"""add_openrouter_and_image_ai_settings

Revision ID: d531a46572af
Revises: c3d4e5f6a7b8
Create Date: 2026-05-25 11:05:16.808712
"""
from alembic import op
import sqlalchemy as sa


revision = 'd531a46572af'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_openrouter_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_image_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_image_model', sa.String(length=100), nullable=True))
        batch_op.drop_column('encrypted_cloudflare_api_key')
        batch_op.drop_column('cloudflare_account_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudflare_account_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('encrypted_cloudflare_api_key', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('ai_image_model')
        batch_op.drop_column('ai_image_provider')
        batch_op.drop_column('encrypted_openrouter_api_key')

    # ### end Alembic commands ###

